### ISSUE TITLE
No such file or directory: 'ghostnet.log'

### ISSUE THREAD

**Issue by karansthr** [t7hm1/GhostNET#1]
```
Traceback (most recent call last):
  File "/usr/bin/ghostnet", line 463, in <module>
    check()
  File "/usr/bin/ghostnet", line 434, in check
    with open('ghostnet.log','r') as logf:
FileNotFoundError: [Errno 2] No such file or directory: 'ghostnet.log'
```
Followed the instruction but got this. My distro is Manjaro

**Comment by st-mich43l** [comment]
@karansthr sorry for that mistake please remove your old GhostNET repo, re-clone it and check the new installation in README.md
